# Generated by Django 6.0.4 on 2026-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=68428902, max_length=20),
            preserve_default=False,
        ),
    ]
